### ISSUE TITLE
Move search field to the left

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#1317]
For the moment, the search field is on the very right

<img width="2160" height="1620" alt="Image" src="https://github.com/user-attachments/assets/da6bc336-db8e-4576-bad0-d0c1f7f52b43" />

I would prefer to have left, on the right of the history navigation button because:
* this is how it is on a browser
* this is like it is on other ports of kiwix
* search resukts would be displayed directly below the search box

**Comment by kelson42** [comment]
@BPerlakiH It seems this is not fixed or not part of yesterday testflight release.


See

<img width="2160" height="1620" alt="Image" src="https://github.com/user-attachments/assets/56e44266-fc08-4881-a356-ae906ee5395f" />

**Comment by BPerlakiH** [comment]
This is fixed, but not included in Testflight.
The [fixing PR](https://github.com/kiwix/kiwix-apple/pull/1318) was dependent on and merged onto: https://github.com/kiwix/kiwix-apple/pull/1319
which in turn was merged into main yesterday.

I can create a new testflight build if needed.

**Comment by kelson42** [comment]
@BPerlakiH Pretty much a mess! I still don't get exactly what you have done but please don't do that anymore. Base or rebase your PR always on git main HEAD before requesting review.
