### ISSUE TITLE
[REGRESSION] Opening app with ZIM doesnt open ZIM

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-apple#962]
When opening Kiwix by double-cliking a ZIM file or using `open` command, the App starts and displays the last viewed ZIM.

I am expecting the clicked ZIM to be opened instead

**Comment by rgaudin** [comment]
macOS 14.6.1 / Kiwix 3.5.1

**Comment by kelson42** [comment]
@rgaudin @BPerlakiH Do we know if this is a regression?

**Comment by rgaudin** [comment]
Well we had #699 and #850

**Comment by kelson42** [comment]
OK, so this is a regression. To be fixed in priority!

**Comment by BPerlakiH** [comment]
I managed to reliably reproduce it.
There are 2 ways to exit the macOS application:
1) closing all windows (one by one), either via the red X system button (top left corner of the window) or pressing CMD+W on each window. Once the last window is closed, the app will exit.
2) Regardless of the amount of windows open, pressing CMD+Q, will exit the app immediatelly.

So what is the difference?
In case 1) we close the window, and delete the tab / window data, as the user closed it, so it's no longer needed.
In case 2) we save data from the windows, in order to restore it on next launch. This mechanism of restoring the windows is not fully working.
There's a built in SwiftUI way to handle this specific feature, but so far it was working only for so called "[Document based app](https://developer.apple.com/documentation/swiftui/building-a-document-based-app-with-swiftui)".

**Comment by kelson42** [comment]
@BPerlakiH We should secure that both way of quitting trigger the same quit() procedure where we do our stuff.

**Comment by BPerlakiH** [comment]
So the way I see it is:
We can have multiple windows, therefore closing a window, and deleting (not storing) any data related to that, is the correct behaviour.
- closing the last window, closes the application, this is also correct.
- saving the state of the windows and restoring it could be a nice to feature, but it's not working properly on macOS, and I checked it wasn't fully working (not even in the oldest available TestFlight build: 3.4.0 (163)). This implementation is restoring only 1 window, and not all of them, which leads to this bug.

For these reasons, I am proposing, to remove this semi-working window restore solution we have, which solves this specific bug. Then create a new issue, to implement the windows management for macOS. It's really an edge case, since the only way to use this feature is to use CMD+Q or from the App Menu choose Quit Kiwix.

**Comment by kelson42** [comment]
@BPerlakiH Top Prio. Would be really great if you find a way to ensure this is the last time we reopen the issue?
![image](https://github.com/user-attachments/assets/0d5116fb-4d6a-4a76-b970-9fc3cd23578a)

**Comment by BPerlakiH** [comment]
> Don't know how that's possible as the fixing PR was tested by me and worked but using released 3.5.2, it's not working.

I have double checked it, and downloaded the App Store version, and it works for opening ZIM files, both when the app is closed, and when the app is already opened.

Maybe worth to double check if you don't have another copy of an older application, or clear the folder before installing.

**Comment by rgaudin** [comment]
I checked before reopening and I don't. I am using the DMG distributed version though.

On a second thought, I find it unreasonable to prevent users from having multiple versions on the app anyway. Double-clicking a ZIM ends up launching on app, so that app has been found by the system and was probably passed the filename.
If there's a macOS bug regarding this, we should gather evidence online or open a ticket upstream

**Comment by BPerlakiH** [comment]
Ok, we narrowed it down during our call with @rgaudin , it seems to be a macOS Sequoia (15.0) issue.

**Comment by BPerlakiH** [comment]
I will be updating to Sequoia, just wanted to wait a bit with it, as there's no way back (downgrade), so won't be able to test the apps on "older" macOS.

**Comment by kelson42** [comment]
@BPerlakiH How does it look like now?

**Comment by benoit74** [comment]
> I will be updating to Sequoia, just wanted to wait a bit with it, as there's no way back (downgrade), so won't be able to test the apps on "older" macOS.

I'm still on Sonoma, and I will stay on it until this issue is fixed, so that we can still test it on old MacOS. Unless this takes months, but I hope it will be fixed soon ^^

**Comment by BPerlakiH** [comment]
It should be working now with the latest TestFlight build.

**Comment by rgaudin** [comment]
Tested on macOS. Works.

- cold start: starts the app and the window with the content is present
- opened-app: adds a window with the ZIM

Two comments:

- on cold start, I still have an extra window with the local library. I believe it's a different issue but worth mentioning here.
- on started kiwix, the created window appear to start with local library then switch to the content URL

https://github.com/user-attachments/assets/10f5562d-7e61-439b-a857-d107bfd88e34

**Comment by benoit74** [comment]
> It should be working now with the latest TestFlight build.

Which build number please? I still have 181 which is dated 4. Nov. 2024

**Comment by kelson42** [comment]
> on cold start, I still have an extra window with the local library. I believe it's a different issue but worth mentioning here.
> On started kiwix, the created window appear to start with local library then switch to the content URL

@BPerlakiH can you please fix both bugs?

**Comment by benoit74** [comment]
With 182 on MacOS Sonoma, I have the same behavior as rgaudin

**Comment by BPerlakiH** [comment]
I have fixed the loading issue, the other issue, multiple windows is more related to this: 
https://github.com/kiwix/kiwix-apple/issues/1015

In short it can happen if you have a previously "saved" window. If you start from scratch, or keep repeating:
- closing all the windows, open the app by clicking on a ZIM file,
It's not occurring anymore.
